FROM golang:latest as builder
WORKDIR /go/src/github.com/jicg/App
COPY . .
#RUN go get github.com/tools/godep
RUN go get
RUN go build -a -ldflags="-w -s"

FROM scratch as final
MAINTAINER jicg <284077319@qq.com>
WORKDIR /app
COPY --from=builder /go/src/github.com/jicg/App/App /app/App
COPY --from=builder /go/src/github.com/jicg/App/views /app/views
COPY --from=builder /go/src/github.com/jicg/App/static /app/static
COPY --from=builder /go/src/github.com/jicg/App/conf /app/conf
EXPOSE 8080
ENTRYPOINT ["/app/App"]